version: '3'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: using-redis
    depends_on:
      - db
      - redis-server
    links:
      - db
      - redis-server
    ports:
      - '3000:3000'
    command: npm run dev

  db:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
  
  redis-server:
    image: 'redis'
    container_name: redis
    ports:
      - '6379:6379'